//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWWCFServiceApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebTracker
    {
        public int Id { get; set; }
        public string URLRequest { get; set; }
        public string SourceIP { get; set; }
        public Nullable<System.DateTime> TimeOfAction { get; set; }
    }
}
